version: 2

python:
    install:
        - requirements: requirements.txt
        - requirements: requirements_dev.txt
        - requirements: requirements_doc.txt
        - method: pip
          path: .

build:
    os: ubuntu-lts-latest
    tools:
        python: "3"

sphinx:
    configuration: docs/conf.py
